<script setup lang="ts">
import { nextTick, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { createGuideSession, getGuideMessages, sendGuideMessage } from '@/api/guide'
import type { GuideMessage } from '@/types/reading'
const route=useRoute();const sessionId=ref('');const messages=ref<GuideMessage[]>([]);const draft=ref('');const loading=ref(true);const sending=ref(false);const error=ref('');const list=ref<HTMLElement|null>(null)
async function bottom(){await nextTick();list.value?.scrollTo({top:list.value.scrollHeight,behavior:'smooth'})}
async function init(){loading.value=true;try{const readingId=typeof route.query.readingId==='string'?route.query.readingId:null;const s=await createGuideSession(readingId);sessionId.value=s.session_id;messages.value=(await getGuideMessages(s.session_id)).items;if(!messages.value.length)messages.value=[{id:'welcome',role:'assistant',content:readingId?'What part of this reading stayed with you?':'What has been staying with you?',created_at:new Date().toISOString()}];await bottom()}catch(e){error.value=e instanceof Error?e.message:'The guide could not be reached.'}finally{loading.value=false}}
async function send(){const content=draft.value.trim();if(!content||sending.value)return;messages.value.push({id:`local-${Date.now()}`,role:'user',content,created_at:new Date().toISOString()});draft.value='';sending.value=true;await bottom();try{messages.value.push(await sendGuideMessage(sessionId.value,content));await bottom()}catch(e){error.value=e instanceof Error?e.message:'Your message could not be sent.'}finally{sending.value=false}}
onMounted(()=>void init())
</script>
<template><main class="page"><header><p>AI TAROT GUIDE</p><h1>Stay with what surfaced.</h1></header><p v-if="loading">Opening a quiet space…</p><section v-else class="shell"><div ref="list" class="messages"><article v-for="m in messages" :key="m.id" :class="['message',m.role]"><small>{{m.role==='assistant'?'LunaArc':'You'}}</small><p>{{m.content}}</p></article><p v-if="sending">LunaArc is reflecting…</p></div><form @submit.prevent="send"><textarea v-model="draft" rows="2" maxlength="2000" placeholder="Write what is still on your mind…" @keydown.enter.exact.prevent="send"/><button :disabled="sending||!draft.trim()">Send →</button></form><p v-if="error" class="error">{{error}}</p></section></main></template>
<style scoped>.page{min-height:100vh;display:grid;grid-template-columns:minmax(280px,.72fr) minmax(420px,1.28fr);gap:60px;padding:70px clamp(24px,6vw,100px);background:radial-gradient(circle at 72% 18%,rgba(117,144,205,.24),transparent 35%),#0d1a4a;color:#fff}header p{margin:0;color:#8fa3d0;font-size:.68rem;font-weight:700;letter-spacing:.18em}header h1{margin:20px 0;font-size:clamp(3.5rem,7vw,7.5rem);font-weight:450;line-height:.9;letter-spacing:-.07em}.shell{min-height:calc(100vh - 140px);display:grid;grid-template-rows:minmax(0,1fr) auto auto;border:1px solid rgba(255,255,255,.18);border-radius:30px;background:rgba(255,255,255,.07);backdrop-filter:blur(22px);overflow:hidden}.messages{overflow-y:auto;padding:32px}.message{max-width:78%;margin-bottom:24px}.message.user{margin-left:auto}.message small{color:#8fa3d0}.message p{margin:8px 0 0;padding:16px 18px;border-radius:20px;background:rgba(255,255,255,.08);line-height:1.65}.message.user p{background:rgba(183,198,232,.16)}form{display:grid;grid-template-columns:1fr auto;gap:12px;padding:18px;border-top:1px solid rgba(255,255,255,.1)}textarea{resize:none;padding:14px 16px;border:0;border-radius:16px;background:rgba(255,255,255,.1);color:#fff;font:inherit;outline:none}button{padding:0 20px;border:1px solid rgba(255,255,255,.2);border-radius:16px;background:rgba(255,255,255,.12);color:#fff}.error{padding:0 18px 18px;color:#9faed0}@media(max-width:900px){.page{grid-template-columns:1fr}.shell{min-height:70vh}}</style>
